# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8767aefe1bc28d9a468e86974e9abaf182e4436d0ceb290c702e81ee1f08e868c2b50ab33d4a2634d74e20e811d3df066b0c63fea8e1ce9d183bc8003f8ea33f

test:
  secret_key_base: e714505ef1d2ef21b66971046002cadfa3696dada3e16ea6a06d608f22952326533a07169a2f15591159b28451b069dbe22187d8c7656c9f1e7c67f46b3294be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
